spring:
  datasource:
    url: jdbc:h2:mem:items
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  profiles:
    active: localhost
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
