services:
  redis:
    image: "redis:7.0.11-alpine"
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  rabbitmq:
    image: "rabbitmq:3.12-management-alpine"
    ports:
      - '5672:5672'
      - '15672:15672'
  store:
    image: "docker.io/library/store:0.0.1-SNAPSHOT"
    ports:
      - '8080:8080'
    environment:
      - SPRING_CACHE_TYPE=redis
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_RABBITMQ_HOST=rabbitmq
volumes:
  redis_data:
    driver: local
