services:
  redis:
    image: "redis:7.0.11-alpine"
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data
  rabbitmq:
    image: "rabbitmq:3.12-management-alpine"
    ports:
      - '5672:5672'
      - '15672:15672'
volumes:
  redis_data:
    driver: local
